FROM node:latest

RUN mkdir -p /usr/src/sample-communication

COPY  ../../dist/apps/sample-communication/*  /usr/src/sample-communication/

WORKDIR /usr/src/sample-communication




RUN yarn 

CMD node ./main.js





 
